spring.application.name=CareerBridge
spring.data.mongodb.uri=mongodb+srv://shravanikorde:root@cluster0.dxhuqgf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=Job
server.port=8080